### ISSUE TITLE
Unhandled Promise Rejection when running into Rate Limiting Errors

### ISSUE THREAD

**Issue by simOneAudi** [contentful/contentful-management.js#1428]
Hi there,

I think we stumbled upon an issue with error handling in this package when using the `raw` API:

All promises returned by API calls are handled using the pattern `.then((response) => response.data, errorHandler)`, for example [here](https://github.com/contentful/contentful-management.js/blob/master/lib/adapters/REST/endpoints/raw.ts#L16). The referenced `errorHandler` function is defined in the `contentful-sdk-core` package. It applies some transformations to the error response before [throwing an exception in line 76](https://github.com/contentful/contentful-sdk-core/blob/master/src/error-handler.ts#L76).

This means, that this error handler must not be used within `.catch()` blocks for promises as it results in an unhandled promise rejection error, making it impossible for the caller to properly handle any errors, or even terminating the whole application depending on the `node` version.

In our case, this happens when running into rate limits: instead of retrying the request, the whole process terminates.

**Comment by simOneAudi** [comment]
Hi,

I tried to work on a snippet for reproducing this, but I wasn't able to do so. The only thing I can provide to you are the logs of that incident. 

So basically what we're are doing is running many content model migrations at once, using AWS Lambda functions. So when migrating many content models in parallel the issue happens most of the times. Although there are a lot of rate limiting errors before, at some point one of the errors raises an `unhandledRejection` event, terminating the whole Lambda.

```
2022-06-30T17:45:22.928Z    abab372c-9112-4071-8046-71587eb75c37    INFO    [SUCCESS]   Update Content Type feature-app-iframe
2022-06-30T17:45:22.928Z	abab372c-9112-4071-8046-71587eb75c37	INFO	[STARTED]   Update field controls for Content Type feature-app-iframe
2022-06-30T17:45:22.928Z    abab372c-9112-4071-8046-71587eb75c37    INFO    [STARTED]   Update field controls for Content Type feature-app-iframe
2022-06-30T17:45:22.929Z    abab372c-9112-4071-8046-71587eb75c37    INFO    [STARTED]   Making requests
2022-06-30T17:45:22.929Z    abab372c-9112-4071-8046-71587eb75c37    INFO    [TITLE]     Making requests (1/1)
2022-06-30T17:45:22.929Z	abab372c-9112-4071-8046-71587eb75c37	INFO	[DATA]      PUT /content_types/feature-app-iframe/editor_interface at V14
2022-06-30T17:45:22.946Z    abab372c-9112-4071-8046-71587eb75c37    INFO    [warning]   Rate limit error occurred. Waiting for 1569 ms before retrying...
2022-06-30T17:45:22.974Z    abab372c-9112-4071-8046-71587eb75c37    INFO    [warning]   Rate limit error occurred. Waiting for 1509 ms before retrying...
2022-06-30T17:45:22.975Z    abab372c-9112-4071-8046-71587eb75c37    INFO    [warning]   Rate limit error occurred. Waiting for 1599 ms before retrying...
2022-06-30T17:45:22.989Z	abab372c-9112-4071-8046-71587eb75c37	INFO	[warning]   Rate limit error occurred. Waiting for 1553 ms before retrying...
2022-06-30T17:45:23.003Z	abab372c-9112-4071-8046-71587eb75c37	ERROR	            Unhandled Promise Rejection 	
```

And here is the JSON object logged for the error:

```json
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "RateLimitExceeded: {\n  \"status\": 429,\n  \"statusText\": \"Too Many Requests\",\n  \"message\": \"You have exceeded the rate limit of this Space by making too many API requests within a short timespan. Please wait a moment before trying the request again.\",\n  \"details\": {},\n  \"request\": {\n    \"url\": \"/spaces/62h.../environments/master/content_types/feature-app-hybrid/published\",\n    \"headers\": {\n      \"Accept\": \"application/json, text/plain, */*\",\n      \"Content-Type\": \"application/vnd.contentful.management.v1+json\",\n      \"X-Contentful-User-Agent\": \"sdk contentful-management.js/8.2.2; platform node.js/v14.19.3; os Linux/v14.19.3;\",\n      \"Authorization\": \"Bearer ...mj2gs\",\n      \"user-agent\": \"node.js/v14.19.3\",\n      \"Accept-Encoding\": \"gzip\",\n      \"X-Contentful-Version\": 9\n    },\n    \"method\": \"put\",\n    \"payloadData\": null\n  },\n  \"requestId\": \"ad0687bd-f17e-4fb1-bdbc-e461faf0b3a3\"\n}",
    "reason": {
        "errorType": "RateLimitExceeded",
        "errorMessage": "{\n  \"status\": 429,\n  \"statusText\": \"Too Many Requests\",\n  \"message\": \"You have exceeded the rate limit of this Space by making too many API requests within a short timespan. Please wait a moment before trying the request again.\",\n  \"details\": {},\n  \"request\": {\n    \"url\": \"/spaces/62h.../environments/master/content_types/feature-app-hybrid/published\",\n    \"headers\": {\n      \"Accept\": \"application/json, text/plain, */*\",\n      \"Content-Type\": \"application/vnd.contentful.management.v1+json\",\n      \"X-Contentful-User-Agent\": \"sdk contentful-management.js/8.2.2; platform node.js/v14.19.3; os Linux/v14.19.3;\",\n      \"Authorization\": \"Bearer ...mj2gs\",\n      \"user-agent\": \"node.js/v14.19.3\",\n      \"Accept-Encoding\": \"gzip\",\n      \"X-Contentful-Version\": 9\n    },\n    \"method\": \"put\",\n    \"payloadData\": null\n  },\n  \"requestId\": \"ad0687bd-f17e-4fb1-bdbc-e461faf0b3a3\"\n}",
        "name": "RateLimitExceeded",
        "message": "{\n  \"status\": 429,\n  \"statusText\": \"Too Many Requests\",\n  \"message\": \"You have exceeded the rate limit of this Space by making too many API requests within a short timespan. Please wait a moment before trying the request again.\",\n  \"details\": {},\n  \"request\": {\n    \"url\": \"/spaces/62h.../environments/master/content_types/feature-app-hybrid/published\",\n    \"headers\": {\n      \"Accept\": \"application/json, text/plain, */*\",\n      \"Content-Type\": \"application/vnd.contentful.management.v1+json\",\n      \"X-Contentful-User-Agent\": \"sdk contentful-management.js/8.2.2; platform node.js/v14.19.3; os Linux/v14.19.3;\",\n      \"Authorization\": \"Bearer ...mj2gs\",\n      \"user-agent\": \"node.js/v14.19.3\",\n      \"Accept-Encoding\": \"gzip\",\n      \"X-Contentful-Version\": 9\n    },\n    \"method\": \"put\",\n    \"payloadData\": null\n  },\n  \"requestId\": \"ad0687bd-f17e-4fb1-bdbc-e461faf0b3a3\"\n}",
        "stack": [
            "RateLimitExceeded: {",
            "  \"status\": 429,",
            "  \"statusText\": \"Too Many Requests\",",
            "  \"message\": \"You have exceeded the rate limit of this Space by making too many API requests within a short timespan. Please wait a moment before trying the request again.\",",
            "  \"details\": {},",
            "  \"request\": {",
            "    \"url\": \"/spaces/62h.../environments/master/content_types/feature-app-hybrid/published\",",
            "    \"headers\": {",
            "      \"Accept\": \"application/json, text/plain, */*\",",
            "      \"Content-Type\": \"application/vnd.contentful.management.v1+json\",",
            "      \"X-Contentful-User-Agent\": \"sdk contentful-management.js/8.2.2; platform node.js/v14.19.3; os Linux/v14.19.3;\",",
            "      \"Authorization\": \"Bearer ...mj2gs\",",
            "      \"user-agent\": \"node.js/v14.19.3\",",
            "      \"Accept-Encoding\": \"gzip\",",
            "      \"X-Contentful-Version\": 9",
            "    },",
            "    \"method\": \"put\",",
            "    \"payloadData\": null",
            "  },",
            "  \"requestId\": \"ad0687bd-f17e-4fb1-bdbc-e461faf0b3a3\"",
            "}",
            "    at errorHandler (/var/task/index.js:2293:23)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: RateLimitExceeded: {",
        "  \"status\": 429,",
        "  \"statusText\": \"Too Many Requests\",",
        "  \"message\": \"You have exceeded the rate limit of this Space by making too many API requests within a short timespan. Please wait a moment before trying the request again.\",",
        "  \"details\": {},",
        "  \"request\": {",
        "    \"url\": \"/spaces/62h.../environments/master/content_types/feature-app-hybrid/published\",",
        "    \"headers\": {",
        "      \"Accept\": \"application/json, text/plain, */*\",",
        "      \"Content-Type\": \"application/vnd.contentful.management.v1+json\",",
        "      \"X-Contentful-User-Agent\": \"sdk contentful-management.js/8.2.2; platform node.js/v14.19.3; os Linux/v14.19.3;\",",
        "      \"Authorization\": \"Bearer ...mj2gs\",",
        "      \"user-agent\": \"node.js/v14.19.3\",",
        "      \"Accept-Encoding\": \"gzip\",",
        "      \"X-Contentful-Version\": 9",
        "    },",
        "    \"method\": \"put\",",
        "    \"payloadData\": null",
        "  },",
        "  \"requestId\": \"ad0687bd-f17e-4fb1-bdbc-e461faf0b3a3\"",
        "}",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:412:35)",
        "    at processPromiseRejections (internal/process/promises.js:245:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"
    ]
}
```

And `   at errorHandler (/var/task/index.js:2293:23)` actually points to the mentioned `errorHandler` from the `contentful-sdk-core` package.

All that code is executed within a call to `runMigration` from the `contentful-migration` package, wrapped by `try`/`catch`, so I don't understand why an unhandled reject occurs.

Hope this helps somehow!

Thanks for your support. 🙏

**Comment by simOneAudi** [comment]
Thanks for the investigation, @andreascful!

After a second look I have to agree with you: the error handler is probably not the root issue. Sorry for that misinformation!

I think we will continue our investigation during the next weeks. I will come back to you, once I figured it out or can provide a snippet reproducing the error.

I guess the issue can be closed until then 😉
