### ISSUE TITLE
ECONNABORTED trying to fetch content with contentful-management

### ISSUE THREAD

**Issue by nenadg** [contentful/contentful-management.js#1884]
Hi all,
I'm receiving the following error for few hours now and I can't find anything documented. This is the error output I get:

```
Error: timeout of 30000ms exceeded
    at createError (/src/node_modules/contentful/dist/contentful.node.js:1005:15)
    at RedirectableRequest.handleRequestTimeout (/src/node_modules/contentful/dist/contentful.node.js:372:16)
    at Object.onceWrapper (events.js:519:28)
    at RedirectableRequest.emit (events.js:400:28)
    at Timeout._onTimeout (/src/node_modules/contentful/dist/contentful.node.js:4267:13)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  config: {
    url: 'entries',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/vnd.contentful.delivery.v1+json',
      'X-Contentful-User-Agent': 'sdk contentful.js/0.0.0-determined-by-semantic-release; platform node.js/v14.21.3; os Linux/4.18.0-477.15.1.el8_8.x86_64;',
      Authorization: 'Bearer [bearer]',
      'user-agent': 'node.js/v14.21.3',
      'Accept-Encoding': 'gzip',
      host: 'cdn.contentful.com:443'
    },
    proxy: { host: 'proxy.lan', port: '8080' },
    params: {
      content_type: '[contentType]',
      skip: 0,
      limit: 10,
      include: 10,
      locale: '*'
    },
    baseURL: 'https://cdn.contentful.com:443/spaces/[spaceId]/environments/master',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    paramsSerializer: [Function (anonymous)],
    timeout: 30000,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: 1073741824,
    maxBodyLength: -1,
    httpAgent: false,
    httpsAgent: false,
    validateStatus: [Function: validateStatus],
    logHandler: [Function: logHandler],
    retryOnError: true,
    data: undefined
  },
  code: 'ECONNABORTED',
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] { response: [Array], error: [Array] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: 'https://cdn.contentful.com:443/spaces/[spaceId]/environments/master/entries?content_type=[contentType]&skip=0&limit=10&include=10&locale=%2A',
      method: 'GET',
      headers: [Object],
      agent: false,
      agents: [Object],
      auth: undefined,
      hostname: 'stg-proxy.gtstg.lan',
      port: '8080',
      nativeProtocols: [Object],
      pathname: 'https://cdn.contentful.com:443/spaces/[spaceId]/environments/master/entries',
      search: '?content_type=[contentType]&skip=0&limit=10&include=10&locale=%2A'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'GET https://cdn.contentful.com:443/spaces/[spaceId]/environments/master/entries?content_type=[contentType]&skip=0&limit=10&include=10&locale=%2A HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/vnd.contentful.delivery.v1+json\r\n' +
        'X-Contentful-User-Agent: sdk contentful.js/0.0.0-determined-by-semantic-release; platform node.js/v14.21.3; os Linux/4.18.0-477.15.1.el8_8.x86_64;\r\n' +
        'Authorization: Bearer [bearer]\r\n' +
        'user-agent: node.js/v14.21.3\r\n' +
        'Accept-Encoding: gzip\r\n' +
        'host: cdn.contentful.com:443\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: 'https://cdn.contentful.com:443/spaces/[spaceId]/environments/master/entries?content_type=[contentType]&skip=0&limit=10&include=10&locale=%2A',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'stg-proxy.gtstg.lan',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://proxy.lan:8080/https://cdn.contentful.com:443/spaces/[spaceId]/environments/master/entries?content_type=[contentType]&skip=0&limit=10&include=10&locale=%2A',
    _timeout: Timeout {
      _idleTimeout: 30000,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 340839350,
      _onTimeout: [Function (anonymous)],
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: true,
      [Symbol(kHasPrimitive)]: false,
      [Symbol(asyncId)]: 8448712,
      [Symbol(triggerId)]: 8448709
    },
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON],
  attempts: 8467
}
```

*note: space id, content type and some other fields are omitted.

**Comment by nenadg** [comment]
The problem seems to be now resolved, so I'm closing this ticket.
