### ISSUE TITLE
`_.partial is not a function` -> Upstream dependency issue? 

### ISSUE THREAD

**Issue by jblock** [contentful/contentful-management.js#41]
Hi! I'm currently working on getting [contentful-space-sync](https://github.com/contentful/contentful-space-sync) set up with our chatbot, and am running into some issues with some of its upstream dependencies. In particular, this library is throwing some errors:

```
Unhandled rejection TypeError: _.partial is not a function
  at Client.redefine.Class.getSpace (/Users/jasonblock/code/trunkbot/node_modules/contentful-space-sync/node_modules/contentful-batch-libs/node_modules/contentful-management/index.js:165:49)
  at /Users/jasonblock/code/trunkbot/node_modules/contentful-space-sync/node_modules/contentful-batch-libs/get/get-source-space.js:63:31
  at tryCatcher (/Users/jasonblock/code/trunkbot/node_modules/contentful-space-sync/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/Users/jasonblock/code/trunkbot/node_modules/contentful-space-sync/node_modules/bluebird/js/release/promise.js:503:31)
  at Promise._settlePromise (/Users/jasonblock/code/trunkbot/node_modules/contentful-space-sync/node_modules/bluebird/js/release/promise.js:560:18)
  at Promise._settlePromise0 (/Users/jasonblock/code/trunkbot/node_modules/contentful-space-sync/node_modules/bluebird/js/release/promise.js:605:10)
  at Promise._settlePromises (/Users/jasonblock/code/trunkbot/node_modules/contentful-space-sync/node_modules/bluebird/js/release/promise.js:684:18)
  at Async._drainQueue (/Users/jasonblock/code/trunkbot/node_modules/contentful-space-sync/node_modules/bluebird/js/release/async.js:126:16)
  at Async._drainQueues (/Users/jasonblock/code/trunkbot/node_modules/contentful-space-sync/node_modules/bluebird/js/release/async.js:136:10)
  at Immediate.Async.drainQueues [as _onImmediate] (/Users/jasonblock/code/trunkbot/node_modules/contentful-space-sync/node_modules/bluebird/js/release/async.js:16:14)
  at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I took a look and `underscore-contrib` does not include `_.partial` as a function at version 0.2.2 (nor does it in any newer versions). What I'm still attempting to wrap my head around is why this library was functioning as of last Friday, as there have been no changes in either contentful utility during that duration.

Also, when pulling the repository locally, tests appear to pass on `master`, so for whatever reason the code that uses `_.partial` isn't covered by the unit tests. Is this anything you can replicate on your end?

Happy to help wherever I can! I can provide more info as needed. The tests were run under Node 0.10.42, and `contentful-space-sync` was run under Node 4.4.0 & 0.12.9 (the only difference between the errors for each node version was the specificity in the error message--4.4.0 went right to `_.partial`, while 0.12.9 was just `undefined is not a function`)

**Comment by jblock** [comment]
Ah, never mind. I noticed that `underscore-contrib` will defer to your previously installed version of `underscore`: https://github.com/documentcloud/underscore-contrib/blob/master/package.json#L6

Now it looks good on my end! Closing this silly issue because it's silly :D

**Comment by trodrigues** [comment]
No worries :) I still don't exactly understand how you got the issue in the first place anyway, which worries me a bit.

In any case, this library is due for a cleanup/rewrite of some parts at some point in the nearish future, so I'll keep that in mind when doing that work.

**Comment by jblock** [comment]
Good to know :+1: . I ended up figuring that our application consuming `contentful-space-sync` was using underscore version `1.3.x`, and `underscore-contrib` was deferring said previously installed version because of its `*` version. And `1.3.x` just happens to not have several of the underscore functions this library was using. It was working as expected--it was just a little opaque.
