### ISSUE TITLE
Given v7.* when createUpload() or createAssetFromFiles() then 404 

### ISSUE THREAD

**Issue by TjenWellens** [contentful/contentful-management.js#584]
It seems a lot like what they mentioned in this thread:
[createAssetFromFiles upload bug #165](https://github.com/contentful/contentful-management.js/issues/165)

When I try
```
const fs = require('fs');
const uploadStream = fs.createReadStream("some-file.png");

async function main() {
  const space = await client.getSpace(process.env.CONTENTFUL_SPACE)
  const environment = await space.getEnvironment(process.env.CONTENTFUL_ENVIRONMENT)
  console.log(environment)
  environment.createUpload({file: uploadStream})
	.then(upload => {
		console.log(upload)
	})
	.catch(error => {
		console.error(error)
	})
}
main()
```
on `v7.3.1` I get the error
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ClientRequest'
    |     property 'socket' -> object with constructor 'TLSSocket'
    --- property '_httpMessage' closes the circle
    at JSON.stringify (<anonymous>)
    at errorHandler (.../node_modules/contentful-management/dist/contentful-management.node.js:13750:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
When I go in to `contentful-management.node.js:13750`
add a line of logging before it crashes on the JSON.stringify cycle
```
error.name = errorName && errorName !== 'Unknown' ? errorName : `${response === null || response === void 0 ? void 0 : response.status} ${response === null || response === void 0 ? void 0 : response.statusText}`;
console.error(errorData) // I added this
error.message = JSON.stringify(errorData, null, '  ');
```
Then I see the actual error message:
```
{
  status: 404,
  statusText: 'Not Found',
  message: 'Not Found',
  details: {},
  request: {
    url: '/spaces/<my-space-id>/environments/master/uploads', // anonymized my-space-id
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/octet-stream',
      'X-Contentful-User-Agent': 'sdk contentful-management.js/7.3.1; platform node.js/v14.7.0; os macOS/19.6.0;',
      Authorization: 'Bearer ...<my-token>', // anonymized
      'user-agent': 'node.js/v14.7.0',
      'Accept-Encoding': 'gzip'
    },
    method: 'post',
    payloadData: ReadStream {
      ... // removed some stuff
    }
  }
}
```

So thats a problem...

I tried a couple of other v7 versions, but I get a different error.
(something about headers)

If I set my version to 6, it does work.
```
"contentful-management": "6.3.2",
```

**Comment by suevalov** [comment]
Thanks for reporting the issue @TjenWellens, we'll release a new version with a fix today.
